[WIP] Update GNOME Sdk to 43
flathub/com.hack_computer.Clippy.Extension pull request #2
Opened 2022-11-25 08:28 UTC by starnight

Update GNOME Sdk to 43 and add the webkitgtk for the dependency.

2022-12-02 06:38 UTC, starnight commented
This is blocked on https://github.com/endlessm/clippy/pull/21

2022-12-13 10:43 UTC, manuq requested changes

2022-12-13 10:43 UTC, manuq commented on com.hack_computer.Clippy.Extension.json
> +                    "commit": "c5ceb8224f764a07ba25185028b0a3e6c0398cd4"
```suggestion
                    "commit": "fdf650145ae7a672cfbc4ed17ac725cc352e24be"
```

2022-12-13 10:46 UTC, manuq approved these changes

2022-12-13 10:46 UTC, merged